# This is a template workflow for organization-wide SonarQube scanning
# name: SonarQube Scan
# on:
#   push:
#     branches: [main]
#   pull_request:
#     branches: [main]
#
# Run SonarQube analysis using the self-hosted runner.
# Applies to all repos in the organization.

name: SonarQube Scan
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  sonarqube:
    name: Run SonarQube Analysis
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Run SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v6
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
